import numpy as np
nums = np.array([[2,3],[4,5]])
print("creating array \n",nums)
arr = np.ones((3,4))
print("creating array of ones \n",arr)
# print(arr.ndim)
arr2 = np.zeros((3,4))
print("creating array of zeros \n",arr2)
# print(arr2.ndim)
arr3 = np.arange(9)
print("creating array using arange\n",arr3)
arr4 = np.concatenate((arr,arr2),axis=1)
print("array concatenation\n",arr4)
# print(type(nums))
arr5 = nums.astype(float)
print("changing type of array using astype\n",arr5)
# print(type(arr5))
# print(type(nums))
arr6 = np.zeros_like(nums)
print("zeros_like\n",arr6)
arr7 = np.ones_like(nums)
print("ones_like\n",arr7)
arr8 = np.random.random((5,4))
print("creating array using random.random\n",arr8)
arr9 = np.random.randint(4,size=(3,4))
print("creating array using random.randint\n",arr9)
transposed = np.transpose(nums)
print("transposing an array\n",transposed)
arr10 = np.arange(1,13)
newarr = arr10.reshape(4,3)
print("reashape to 4 by 3 dimensional array\n",newarr)
newarr2 = arr10.reshape(4,-1)
print("reshape to 4 and -1 array\n",newarr2)
flattened_array = np.random.randint(5,size=(5,6)).flatten()
print("flattening the array\n",flattened_array)
arrays = np.random.randint(10,size=(3,4,5))
print("indexing")
print(arrays[0][0][0])
print(arrays[1,2,3])
print(arrays[-1,-1][2])
a = np.array([[1,2,3],[3,4,6],[6,7,8]])
b = np.array([[7,6,8],[4,7,4],[7,8,5]])
o = np.matmul(a,b)
o1 = np.dot(a,b)
o2 = np.vdot(a,b)
print("array matmul\n",o)
print("dot product\n",o1)
print("vdot product\n",o2)

#mathematical operations
print("matrix addition \n",np.add(a,b))
print("matrix subtraction \n",np.subtract(a,b))
print("matrix multiplication\n",np.multiply(a,b))
print("matrix division\n",np.divide(a,b))
print("matrix power\n",np.power(a,b))
print("matrix modulus\n",np.mod(a,b))